<h2> ======================================================</h2>
 <h1>MA477 - Theory and Applications of Data Science</h1> 
  <h1>Lesson 2: Introduction to NumPy</h1> 
 
 <h4>Dr. Valmir Bucaj</h4>
 <br>
 United States Military Academy, West Point, AY20-2
<h2>=======================================================</h2>

In [1]:
import numpy as np

<h2>==================================================</h2>
<br>
<h1>HOMEWORK #1</h1>

<h2>=================================================</h2>

<h3> Complete the following exercises. Document your code as necessary.</h3>
<br>

<ol>
<li><font size=3> Create a 5 by 7 numpy array of random integers with values between 3 and 11 inclusive. Then do the following:
    <ol> <li>Check the data type of the array</li>
        <li>Find the maximum of the entire array</li>
        <li>Find the minimum value of each row</li>
        <li>Find the index where the minimum value of each row occurs</li>
    </ol></font></li>
</ol>

In [9]:
arr=np.random.randint(3,11,size=(5,7))

In [10]:
arr

array([[7, 8, 9, 9, 6, 5, 5],
       [4, 4, 8, 6, 8, 9, 4],
       [3, 4, 6, 4, 9, 9, 4],
       [9, 6, 4, 6, 5, 8, 4],
       [9, 3, 7, 8, 9, 5, 8]])

In [11]:
#Your code for part A of Exercise 1 goes here
arr.dtype

dtype('int32')

In [12]:
#Your code for part B of Exercise 1 goes here
arr.max()

9

In [13]:
#Your code for part C of Exercise 1 goes here
arr.min(axis=1)

array([5, 4, 3, 4, 3])

In [14]:
#Your code for part D of Exercise 1 goes here
np.argmin(arr)

14

<ol start='2'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94, 99])
```    
</ol>

In [17]:
#Your code for Exercise 2 goes here
arr1=np.arange(4,104,5)

In [16]:
arr1

array([ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59, 64, 69, 74, 79, 84,
       89, 94])

<ol start='3'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array: </font></li>

```python
#Result
array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])
```    
</ol>

In [39]:
#Your code for Exercise 3 goes here
arr3=arr1.reshape(4,5)

In [40]:
arr3

array([[ 4,  9, 14, 19, 24],
       [29, 34, 39, 44, 49],
       [54, 59, 64, 69, 74],
       [79, 84, 89, 94, 99]])

<ol start='4'>
   
<li> <font size='3'>Create a 4 by 2 by 3 array of normally distributed values</font></li>
   
</ol>

In [30]:
#Your code for Exercise 4 goes here
np.random.rand(4,2,3)

array([[[0.26864687, 0.0524673 , 0.45176331],
        [0.14046024, 0.80398275, 0.76985857]],

       [[0.6366118 , 0.78113774, 0.87673841],
        [0.47225335, 0.76619879, 0.46450827]],

       [[0.50117985, 0.20262037, 0.16108258],
        [0.27590287, 0.08002534, 0.81045116]],

       [[0.18890497, 0.3510632 , 0.96543957],
        [0.28558078, 0.95886686, 0.6310444 ]]])

<ol start='5'>
   
<li> <font size='3'>Enter the code below that generates the following numpy array(including the correct
    data type): </font></li>

```python
#Result
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]]
```    

</ol>

In [31]:
#Your code for Exercise 5 goes here
np.eye(6,k=-2)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.]])

<ol start='6'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])
```    
<ol>
    <li>Enter the code below that selects only the last four elements:</li>

```python
#Result
array([27, 29, 31, 33])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([ 3,  9, 15, 21, 27, 33])
```
</ol>
</ol>

In [32]:
arr6=np.arange(3,34,2)

In [33]:
arr6

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33])

In [35]:
#Your code for part A of Exercise 6 goes here
arr6[-4:]

array([27, 29, 31, 33])

In [37]:
#Your code for part B of Exercise 6 goes here
arr6[arr6%3==0]

array([ 3,  9, 15, 21, 27, 33])

<ol start='7'>
   
<li> <font size='3'>Given the 2D numpy array below </font></li>

```python
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])
```    
<ol>
    <li> Enter the code below that selects the element 72 on the last row</li>
    <br>
   <li>Enter the code below that selects the following subarray:</li>

```python
#Result
array([[76,  3],
       [26, 71],
       [38, 54]])
```
<li>Enter the code that selects the following subarray:

```python
#Result
array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])
```
</ol>
</ol>

In [42]:
arr_2d=np.array([[69, 75, 52, 33,  7, 62, 22],
               [87, 51, 13, 75, 78, 46, 53],
               [43, 24, 58, 76,  3,  3, 57],
               [84, 86, 75, 26, 71, 77,  7],
               [75, 17, 17, 38, 54, 72, 78]])

In [44]:
#Your code for part A of Exercise 7 goes here
arr_2d[-1,-2]

72

In [49]:
#Your code for part B of Exercise 7 goes here
arr_2d[1:4]

array([[87, 51, 13, 75, 78, 46, 53],
       [43, 24, 58, 76,  3,  3, 57],
       [84, 86, 75, 26, 71, 77,  7]])

<ol start='8'>
   
<li> <font size='3'>Given the numpy array below </font></li>

```python
arr=np.arange(1,50,3)
array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])
```    
<ol>
    <li>Enter the code that selects all elements larger than 7 and smaller than 43:

```python
#Result
array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

```
   <li>Enter the code below that selects all even integers larger than 11 and smaller than 45:</li>

```python
#Result
array([16, 22, 28, 34, 40])
```
</ol>
</ol>

In [50]:
arr8=np.arange(1,50,3)

In [51]:
arr8

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [52]:
#Your code for part A of Exercise 8 goes here
arr8[(arr8>7)&(arr8<43)]

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40])

In [54]:
#Your code for part B of Exercise 8 goes here
arr8[(arr8%2==0)&(arr8>11)&(arr8<45)]

array([16, 22, 28, 34, 40])

<ol start='9'>
   
<li> <font size='3'>Create a 1D uniformly distributed array with 20 elements and compute: </font></li>


<ol>
    <li> Mean</li>

   <li>Standard Deviation</li>
   
   <li>Median</li>
   
   <li>Mean of its log values</li>
</ol>
</ol>

In [55]:
#1D uniformly distributed array
arr9=np.random.rand(20)

In [56]:
arr9

array([0.25915737, 0.77773719, 0.33759417, 0.5381362 , 0.750439  ,
       0.35029115, 0.75759495, 0.09264019, 0.82096153, 0.24885692,
       0.84512263, 0.2209881 , 0.33126891, 0.66186311, 0.37894883,
       0.0580824 , 0.62546525, 0.07280929, 0.4963084 , 0.8834982 ])

In [57]:
#Your code for part A of Exercise 9 goes here
np.mean(arr9)

0.47538818908066655

In [58]:
#Your code for part B of Exercise 9 goes here
np.std(arr9)

0.2684461467436326

In [59]:
#Your code for part C of Exercise 9 goes here
np.median(arr9)

0.43762861252758056

In [62]:
#Your code for part D of Exercise 9 goes here
arr9_log=np.log10(arr9)

In [63]:
np.mean(arr9_log) #part 2 of part D

-0.43024264748634583

<ol start='10'>
   
<li> <font size='3'>Write a function that:</font></li>
    <ol>
    <br>
   <li> takes a 1D Numpy array as input and prints out the <b>reversed</b> array with element type float</li>

For example, if you input the following array into your function
```python
array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])
```
your function should print out

```python
array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])
```

<li> takes a 2D Numpy array as input and prints out a copy of the input array <b> flattened</b> to one dimension</li>

For example if the input array is:
```python
array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
```
the output of your function should be
```python
array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])
```
</ol>
</ol>

In [64]:
arr10=np.arange(1,24,2)

In [65]:
arr10

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [77]:
#Your code for part A of Exercise 10 goes here
def reverse_float(a):
    b=np.flip(a)
    c=b.astype(float)
    return c

reverse_float(arr10)

#Citation
#CDT Raftery, A4,'21. Assistance given to the author via visual aid. I sat and struggled to create a function that would do
#the reverse function. I tried various ways given by the example in lesson 2, so I asked Megan how to do it and she explained
#what to do because I was unfamiliar with coding in python. She sent me a picture of her code and I copied it, but I read
#her citations and she helped me with it. I came to her before I searched on the internet, which is why my code would look
#exactly the same as hers. I would not have been able to complete this without her. 
#West Point, NY. 21 Jan 2020.

array([23., 21., 19., 17., 15., 13., 11.,  9.,  7.,  5.,  3.,  1.])

In [80]:
#Your code for part A of Exercise 10 goes here
def flat(a):
    b = a.flatten()
    return b
a = np.array([[7, 4, 8, 3],
       [6, 3, 4, 3],
       [4, 7, 5, 4]])
flat(a)

array([7, 4, 8, 3, 6, 3, 4, 3, 4, 7, 5, 4])

In [ ]:
#Citation
#CDT Raftery, A4,'21. Assistance given to the author via visual aid. I sat and struggled to create a function that would 
#flatten the array. The original picture she had sent to help me with part A also had to code for part B. 
#She sent me a picture of her code and I copied it, but I read
#her citations and she helped me with it. I came to her before I searched on the internet, which is why my code would look
#exactly the same as hers. I would not have been able to complete this without her. 
#West Point, NY. 21 Jan 2020.